[project]
name = "bilibili-get-user-songlist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bilibili-api-python>=17.4.1",
    "curl-cffi>=0.14.0",
]
